### ISSUE TITLE
Center Text (Input)

### ISSUE THREAD

**Issue by Marcosmaliki** [FilippoPaganelli/CruciApp#2]
add this code on the TextField decoration to remove the underline and center the text 

`   focusedBorder:
             OutlineInputBorder(
                      borderSide:
                       BorderSide.none),`

**Comment by Marcosmaliki** [comment]
Can I help you maintain this?

**Comment by FilippoPaganelli** [comment]
Thank you for the suggestion! Looks better after applying this fix. I also updated the kotlin plugin to the latest version and switched to 'mavenCentral' repository from 'jCenter', in android/build.gradle.
